server:
    port: 4000

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: auth
                  uri: lb://auth
                  predicates:
                      - Path=/auth/**
                  order: 0

                - id: recruitme
                  uri: lb://recruitme
                  predicates:
                      - Path=/**
                  order: 1
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
